[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "polytope-client"
license = "Apache-2.0"
license-files = ["LICENSE.txt"]
dynamic = ["version"]

[tool.setuptools_scm]

[tool.black]
line-length = 120
